name: Initializing Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::499989195637:role/git-action-deploy-role
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 mb s3://499989195637-devops-scripts --region us-east-1 2>/dev/null || true
          aws s3 cp init.sql s3://499989195637-devops-scripts/init.sql
          aws s3 cp init.py s3://499989195637-devops-scripts/init.py
          echo "✅ Files uploaded."

  init-db:
    needs: smoke
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Anujkumar-9/Banking-APP
          ref: main

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::499989195637:role/git-action-deploy-role
          aws-region: us-east-1

      - name: Run Database Initialization
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands":[
                "aws s3 cp s3://499989195637-devops-scripts/init.sql /tmp/init.sql",
                "aws s3 cp s3://499989195637-devops-scripts/init.py /tmp/init.py",
                "python3 /tmp/init.py",
                "rm -f /tmp/init.py /tmp/init.sql"
              ]
            }' \
            --query "Command.CommandId" \
            --output text \
            --region us-east-1)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region us-east-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region us-east-1)

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::Database Creation Failed on $FAILED instance(s)!"
            exit 1
          fi

          echo "✅ Database Created Successfully"