name: Deploy

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  VERSION: v1
  IMAGE: 499989195637.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
  REGION: us-east-1
  S3_BUCKET: 499989195637-devops-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: Anujkumar-9/Banking-App
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::499989195637:role/git-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | docker login \
            --username AWS \
            --password-stdin \
            499989195637.dkr.ecr.${{ env.REGION }}.amazonaws.com

          echo "✅ Login Successful to ECR"

      - name: Upload Docker Compose to S3
        run: |
          aws s3 mb s3://${{ env.S3_BUCKET }} --region ${{ env.REGION }} 2>/dev/null || true

          aws s3 cp docker_compose.yml \
            s3://${{ env.S3_BUCKET }}/docker-compose.yml \
            --region ${{ env.REGION }}

          echo "✅ Docker Compose uploaded successfully"